inherit_from: .rubocop_rails.yml
inherit_gem:
  rubocop-discourse: default.yml

require:
- rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50
