services:
  postgres:
    container_name: psychedelic-thousand-sunny-postgres
    hostname: localhost
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'psychedelic-thousand-sunny'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    container_name: psychedelic-thousand-sunny-redis
    image: redis:7.0.4-alpine
    command: redis-server
    hostname: localhost
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis:
