version: '2.1'
orbs:
  ruby: circleci/ruby@1.8.0
jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.1.2'
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:3.1.2'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:3.1.2'
      - environment:
          POSTGRES_DB: psychedelic_thousand_sunny_test
          POSTGRES_PASSWORD: psychedelic-thousand-sunny
          POSTGRES_HOST: 'localhost'
          POSTGRES_USER: root
        image: 'postgres:14.4-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: localhost
      PGPASSWORD: psychedelic-thousand-sunny
      PGUSER: root
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
